envVars:
  - key: NODE_ENV
    value: staging

  - key: APP_SECRET
    generateValue: true

  - key: DB_URL
    fromDatabase:
      name: mydb
      property: connectionString

  - key: STRIPE_API_KEY
    sync: false

  - fromGroup: my-env-group